name: Hello World
on: push
jobs:
  say_hello:
    name: A job to say hello
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - id: hello
      name: Hello world action step
      uses: ./.github/actions/hello-world-action
      with:
        who-to-greet: 'Mona the Octocat'
    - name: Create pull request action step
      uses: peter-evans/create-pull-request@v1.6.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COMMIT_MESSAGE: Add hello file
        COMMIT_AUTHOR_EMAIL: vinayak-mehta@users.noreply.github.com
        COMMIT_AUTHOR_NAME: Vinayak Mehta
        PULL_REQUEST_TITLE: 'Add hello file'
        PULL_REQUEST_BODY: New hello!
        PULL_REQUEST_ASSIGNEES: vinayak-mehta
        PULL_REQUEST_REVIEWERS: vinayak-mehta
        PULL_REQUEST_BRANCH: add-hello
        BRANCH_SUFFIX: short-commit-hash
