name: Hello World
on: push
jobs:
  say_hello:
    name: A job to say hello
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - id: hello
      name: Hello world action step
      uses: ./.github/actions/hello-world-action
      with:
        who-to-greet: 'Mona the Octocat'
    - name: Commit file step
      run: |
        git config --global user.name 'Vinayak Mehta'
        git config --global user.email 'vinayak-mehta@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/vinayak-mehta/conrad
        git checkout -b add-hello-file
        git commit -am "Add hello file"
        git push origin add-hello-file
