name: Get events
on: push

jobs:
  get_pycon_events:
    name: Crawler to get PyCon events
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - id: hello
      name: Get events action step
      uses: ./.github/actions/get-events-action
      with:
        crawler-name: 'PyConCrawler'
  raise_pull_request:
    name: Raise a pull request with latest events
    runs-on: ubuntu-latest
    steps:
    - name: Create pull request action step
      uses: peter-evans/create-pull-request@v1.6.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COMMIT_MESSAGE: Add hello file
        COMMIT_AUTHOR_EMAIL: vinayak-mehta@users.noreply.github.com
        COMMIT_AUTHOR_NAME: Vinayak Mehta
        PULL_REQUEST_TITLE: 'Add hello file'
        PULL_REQUEST_BODY: New hello!
        PULL_REQUEST_ASSIGNEES: vinayak-mehta
        PULL_REQUEST_REVIEWERS: vinayak-mehta
        PULL_REQUEST_BRANCH: add-hello
        BRANCH_SUFFIX: short-commit-hash
